spring.datasource.url: jdbc:h2:file:./camunda-h2-database

camunda:
  bpm:
    admin-user:
      id: demo
      password: demo
    authorization:
      enabled: true
spring:
  datasource:
    url: jdbc:postgresql://ru.dmitriy.space:31460/itmo
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update

  mail:
    username: bermasdenis@yandex.com
    password:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: ru.dmitriy.space:31411
    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"

#spring:
#  security:
#    user:
#      name: demo
#      password: demo

#logging:
#  level:
#    org.camunda.bpm.engine.impl.persistence.entity: DEBUG
#    org.camunda.bpm.engine: DEBUG
